export function useIconMap() {
    const map = new Map<string, string>()
    map.set("wen-zhang", "&#xe659;")
        .set("sou-suo", "&#xe8b9;")
        .set("dark-theme", "&#xe65a;")
        .set("mu-lu", "&#xe614;")
        .set("warn", "&#xe663;")
        .set("error", "&#xe67a;")
        .set("ti-shi", "&#xe64c;")
        .set("cha", "&#xe609;")
        .set("jian-tou-you", "&#xe62e;")
        .set("jian-tou-shang", "&#xe62d;")
        .set("jian-tou-zuo", "&#xe909;")
        .set("jian-tou-xia", "&#xe62f;")
        .set("guan-yu","&#xe655;")
        .set("dong-tai","&#xe610;")
        .set("wei-xin","&#xe620;")
        .set("you-xiang","&#xe600;")
        .set("ge-ren","&#xe654;")
        .set("dian-zan","&#xe8ad;")
        .set("she-zhi","&#xe8b7;")
        .set("zhu-ye","&#xe8a1")
        .set("wei-xin","&#xe620;")
        .set("wei-xin-2","&#xe607;")
        .set("github","&#xe741;")
        .set("ri-qi","&#xe650;")
        .set("biao-qian","&#xe63d;")
        .set("dui-gou","&#xe65b;")
        .set("cha-2","&#xe630;")
        .set("jia","&#xe65c;")
        .set("tong-lei","&#xe848;")
        .set("shang-chuan","&#xec1d;")
        .set("cai-dan","&#xe60e;")
    return map
}